version: "3.9"

services:
  app:
    container_name: typestacknodejs
    image: typestacknodejs
    build:
      context: .
      target: development
    ports:
      - "5000:5000"

  db:
    container_name: typestacknodejsdb
    image: mysql:8.0.32
    restart: always
    environment:
      MYSQL_DATABASE: typestacknodejsdb
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3306:3306"
    expose:
      - "3306"
    volumes:
      - typestacknodejs-db:/var/lib/mysql

volumes:
  typestacknodejs-db:
